### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getStackClasses' of null

### ISSUE THREAD

**Issue by notmed1** [Peekmo/atom-symfony2#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-symfony2](https://github.com/peekmo/atom-symfony2) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getStackClasses' of null

```
At C:\Users\hamou\.atom\packages\atom-symfony2\lib\providers\service-provider.coffee:31

TypeError: Cannot read property 'getStackClasses' of null
    at ServiceProvider.module.exports.ServiceProvider.getSuggestions (/packages/atom-symfony2/lib/providers/service-provider.coffee:31:33)
    at providers.forEach.provider (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:3249:53)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:1661:30)
```

### Commands

```
  4x -4:13 core:save (input.hidden-input)
     -3:59 find-and-replace:select-next (input.hidden-input)
  4x -3:58.7.0 core:save (input.hidden-input)
     -3:54.3.0 core:backspace (input.hidden-input)
  3x -3:53 core:save (input.hidden-input)
     -3:40.5.0 autocomplete-plus:confirm (input.hidden-input)
     -3:40.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -3:36.2.0 core:save (input.hidden-input)
     -3:00.5.0 core:undo (input.hidden-input)
 11x -2:59.8.0 core:save (input.hidden-input)
  2x -0:46.1.0 core:backspace (input.hidden-input)
     -0:39.1.0 core:copy (input.hidden-input)
     -0:38.9.0 core:paste (input.hidden-input)
  3x -0:30.5.0 core:backspace (input.hidden-input)
     -0:04.7.0 core:copy (input.hidden-input)
     -0:04.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-symfony 1.2.0 
atom-symfony2 0.3.0 
atom-twig 4.2.0 
language-twig 1.6.3 
php-twig 4.0.0 
script 3.17.3 
```

**Comment by christheyounger** [comment]
Any news on why this might be happening, workarounds?

**Comment by romeugodoi** [comment]
It's happend to me too.
