### ISSUE TITLE
Failed to load the atom-symfony2 package

### ISSUE THREAD

**Issue by halfpastfive** [Peekmo/atom-symfony2#6]
[Enter steps to reproduce below:]
1. install in ~/.atom/packages (from release 0.2.1 on github)
2. Open atom, crash appears on launch

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11
**Thrown From**: [atom-symfony2](https://github.com/peekmo/atom-symfony2) package, v0.2.1
### Stack Trace

Failed to load the atom-symfony2 package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/benjamin/.atom/packages/atom-symfony2-0.2.1/lib/providers/services/file-service-provider.coffee:2:14)
    at Object.<anonymous> (/Users/benjamin/.atom/packages/atom-symfony2-0.2.1/lib/providers/services/file-service-provider.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/benjamin/.atom/packages/atom-symfony2-0.2.1/lib/providers/services/yaml-service-provider.coffee:1:23)
    at Object.<anonymous> (/Users/benjamin/.atom/packages/atom-symfony2-0.2.1/lib/providers/services/yaml-service-provider.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/benjamin/.atom/packages/atom-symfony2-0.2.1/lib/atom-symfony2.coffee:6:23)
    at Object.<anonymous> (/Users/benjamin/.atom/packages/atom-symfony2-0.2.1/lib/atom-symfony2.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.1
go-plus, v3.5.1
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

How did you install the package ? Via `apm` ? Because it not find fuzzaldrin which is a nodejs module, so the only explanation that I have is that the dependencies are not downloaded.
